const CREATED = 'EVENT_STATUS_CREATED';
const DONE = 'EVENT_STATUS_DONE';
const WAITING = 'EVENT_STATUS_DONE';
const EXECUTING = 'EVENT_STATUS_EXECUTING';
const UNWINDING = 'EVENT_STATUS_UNWINDING';
const UNWINDED = 'EVENT_STATUS_UNWINDED';
const SCHEDULED = 'EVENT_STATUS_SCHEDULED';

module.exports = {
  CREATED,
  EXECUTING,
  DONE,
  WAITING,
  UNWINDING,
  UNWINDED,
  SCHEDULED
};
